Add support for AirQualitySensor
WebThingsIO/gateway pull request #2598
Opened 2020-10-05 21:33 UTC by tim-hellhake

resolves #2574

2020-10-07 15:38 UTC, mrstegeman requested changes
I think my biggest issue is that we just pick the first concentration/density property to display, but that's what we do for other things as well. Just wish there was a better approach.

2020-10-07 15:38 UTC, mrstegeman commented on static/js/components/capability/air-quality-sensor.js
> + * A bubble showing a air quality sensor icon.
nit: "an air quality"

2020-10-07 15:38 UTC, mrstegeman commented on static/js/schema-impl/capability/air-quality-sensor.js
> + * UI element representing a airquality sensor.
nit: "an air quality"

2020-10-07 15:38 UTC, mrstegeman commented on static/js/schema-impl/capability/air-quality-sensor.js
> +        this.airqualityProperty = name;
nit: `airQualityProperty`

2020-10-08 20:25 UTC, mrstegeman approved these changes

2020-10-08 20:30 UTC, tim-hellhake commented
> I think my biggest issue is that we just pick the first concentration/density property to display, but that's what we do for other things as well. Just wish there was a better approach.

Yeah, me too.
But as long as one device is tied to one _buble_, there is not much we can do.
Maybe we need something like the rule editor where you first pick the device and then the property you want to display.

2020-10-08 20:33 UTC, mrstegeman commented
You mean like in #1826?

2020-10-08 20:33 UTC, merged