Allow no exec member for extension add-ons - closes #3037
WebThingsIO/gateway pull request #3040
Opened 2022-12-13 15:18 UTC by benfrancis

2022-12-13 18:04 UTC, tim-hellhake requested changes

2022-12-13 18:04 UTC, tim-hellhake commented on src/addon-utils.ts
> +  const manifestTemplate: Record<string, any> = {
```suggestion
  const manifestTemplate: Record<string, unknown> = {
```
This would make the linter happy

2022-12-14 00:17 UTC, tim-hellhake commented
> Hmm, that didn't make it happy.

The linter is happy now.
Now it's a compile error.
The `Record` type is the problem.
Before the object type was inferred through the data.
The compiler can no longer guarantee that the properties exist.

> What is the reason for the "no explicit any" rule anyway? It's kind of a pain.

It defeats the purpose of a typesafe language.

2022-12-14 00:20 UTC, tim-hellhake requested changes
Unfortunately, I cannot edit the correct line because it's outside the diff.
But if you want a quick solution it would be
```
    (<Record<string, unknown>>(
      (<Record<string, unknown>>manifest.gateway_specific_settings).webthings
    )).exec = '';
```
in line 125.

2022-12-14 00:20 UTC, tim-hellhake commented on src/addon-utils.ts
> +  const manifestTemplate: Record<string, unknown> = {
```suggestion
  const manifestTemplate = {
```

2022-12-14 00:25 UTC, tim-hellhake commented
> What is the reason for the "no explicit any" rule anyway? It's kind of a pain.

Yes, it's painful but for a reason.
It's a potentially unsafe operation.
The correct way would be to define an interface for the manifest json.
This allows you to specify optional properties.
Or even better: use json schema instead of writing your own validator :grimacing:

2022-12-14 15:22 UTC, tim-hellhake approved these changes

2022-12-14 15:24 UTC, benfrancis commented
> if you want a quick solution it would be
> 
> ```
>     (<Record<string, unknown>>(
>       (<Record<string, unknown>>manifest.gateway_specific_settings).webthings
>     )).exec = '';
> ```
> 
> in line 125.

Thank you! Done.

> Yes, it's painful but for a reason.
> It's a potentially unsafe operation.
> The correct way would be to define an interface for the manifest json.
> This allows you to specify optional properties.

Makes sense, thank you.

Ironic that this rule is probably what caused this bug in the first place... ;)

> Or even better: use json schema instead of writing your own validator grimacing

Yeah it's weird that all the add-on IPC messages are validated using JSON Schema but the add-on manifest is validated like this. I don't know what the history of that is.

2022-12-14 15:54 UTC, merged

2022-12-16 21:52 UTC, flatsiedatsie commented
Awesome, cool that the Square theme will continue to work.